DROP TABLE IF EXISTS TB_HEROES;

CREATE TABLE TB_HEROES (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NAME TEXT NOT NULL,
  POWER TEXT NOT NULL
);

INSERT INTO TB_HEROES (NAME, POWER) 
  VALUES 
    ('BATMAN', 'RICH'),
    ('FLASH', ' SPEED'),
    ('AQUAMAN', 'WATHER');

SELECT * FROM TB_HEROES;

UPDATE TB_HEROES
  SET NAME = 'NARUTO', POWER = 'GOD'
  WHERE ID = 1
  